### ISSUE TITLE
[BUG] Invalid Recipes for Pams

### ISSUE THREAD

**Issue by Seyaboy** [itsdinkd/AQM3#100]
**Modpack Version**
[AQM3 v1.0.4b [1.18.2]
**Minecraft Version**
1.18.2
**Describe the bug**
The bug is that some Pam's Harvestcraft items are missing as ''Empty Tag:forge:crops/peppercorn''
**To Reproduce**
1. Go to 'JEI and search up black pepper' (There are also many missing Empty tags on other type of foods)
2. Click on 'black pepper and look up the recipe'
3. You will see an red error border in the recipes

**Expected behavior**
Some foods is impossible to make as the recipes are critical parts of making the food

**Screenshots**
![Screenshot (24)](https://user-images.githubusercontent.com/28493376/173975286-3d46993b-ab92-48a3-9c74-437d4d3fc769.png)
![Screenshot (25)](https://user-images.githubusercontent.com/28493376/173975313-40d19048-80a4-4593-b793-ee21319243a5.png)

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**
Also there are many other ingredients that has 'empty tags' mainly from Pam's Harvestcraft

**Comment by Seyaboy** [comment]
Edit: I think I found a fix and requires the mods
1. https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees
2. https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops
Two mods have the ingredients that seem to fix the many issues with the 'empty tags' on many foods in pams harvestcraft

**Comment by itsdinkd** [comment]
this is known. I reported it to the developer but its been crinkets since opening up the issue.

**Comment by itsdinkd** [comment]
Trees is for 1.16

**Comment by itsdinkd** [comment]
Closing because dev doesn't care and us MIA
