### ISSUE TITLE
[BUG] Pure Iron Plate recipe consumes cast in Multiservo Press

### ISSUE THREAD

**Issue by RedReign** [itsdinkd/AQM3#101]
**Modpack Version**
1.0.4b

**Minecraft Version**
1.18.2

**Describe the bug**
The only method of creating Pure Iron Plates is through the Multiservo press. Using this method, however, consumes the Small Plate Gold Cast for each operation.

**To Reproduce**
1. Place and power a Multiservo Press block.
2. Insert a Pure Iron Ingot in the top input slot.
3. Insert a Small Plate Gold Cast in the bottom slot.
4. Observe the cast being deleted when the plates are finished casting.

**Expected behavior**
I expected the cast to not be consumed for each operation of the press, as this makes crafting Pure Iron Plates very tedious and expensive.

**Additional context**
I have noticed this issue on a multiplayer server. I have not tested on a singleplayer server.

**Comment by itsdinkd** [comment]
nerfed in 1.0.5
