### ISSUE TITLE
[SUGGESTION] Changing Mekanism Recipes

### ISSUE THREAD

**Issue by error224543** [itsdinkd/AQM3#107]
**Modpack Version**
Server 
**Minecraft Version**
Server
**Describe the Suggestion**
Changing Mekanism Recipes for a better balance

**To Change**
Changing the circuit recipes around for better balance to lategame. The use of materials extremely hard to make and impossible to accumulate makes most machines not desirable and a preferable to avoid both mods. Opals being a 95% chance to delete themselves apron mining without cheesing using a digital miner and the novasteel being still up the chance from the entropy reactors make this harder to actually even begin mekanism as it's not an upward scale, just a flat slope. My recommendation is to maybe edit the lineage of the recipes to better balance them out. Basic circuits could be the same or changed to mystic ingots and the advanced circuits could use the attuned titanium plus another material to keep the balance of all mods, maybe amethyst (from oresabovediaminds) or another mod when ultimate circuits could use the novasteel and opal, as they are the endgame circuits. It could use more thought, but already it's just a pain for advanced circuits and then you use them all up, eventually there will be an impossibility to get opal thanks to it's already hardness to get. Opal is balanced as it is, being how strong it is but the recipes make it not as enjoyable thanks to their complexity and reliance on random chance.

**Comment by itsdinkd** [comment]
Accepted

**Comment by itsdinkd** [comment]
added in 1.6
