### ISSUE TITLE
[BUG] Several recipes missing on server

### ISSUE THREAD

**Issue by Ultraxite** [itsdinkd/AQM3#108]
**Modpack Version**
1.0.5
**Minecraft Version**
1.18.2
**Describe the bug**
After updating to 1.0.5, several recipes in REI are not present on the server, but are present on our individual clients. This includes the angel ring recipe, and the productive bees recipes (specifically breeding recipes and anything used in the mod's centrifuge, the beehive recipes that indicate what a bee produces are fine). Yes, we have looked at the book, and tried to get recipes by looking at the spawn egg's recipe.
**To Reproduce**
No idea - just started after we updated to 1.0.5

**Expected behavior**
When you press R on an item in REI, it generally brings up a recipe. The aforementioned recipes do not appear, but other recipes for other mods work fine.

**Screenshots**
N/A

**Crash log or latest.log.log**
No crashes. No errors.

**Additional context**
This might be related to another bug we are experiencing on the server where every item when R is pressed on it, in addition to its regular recipes also has a bunch of unrelated Thermal Expansion fluid encapsulator recipes. Even items that usually have no recipe will still bring up the unrelated fluid encapsulator recipes. See my AQM3-support thread for more details (discord is Deleno#9004). Again, this wasnt happening prior to 1.0.5, and doesnt happen in singleplayer. We tried deleting and REI and its jei integration fix in the server mod file and it did nothing to help either of these issues. Also, when pressing the tab at the top of REI when looking at recipes to see literally every recipe, the productive bees section has no breeding tab, but does have a beehive tab.

**Comment by itsdinkd** [comment]
Nothing I can do about this unfortunately. It's an issue with productive bees and REI. You can try reporting it to both mods individually along with screenshots. As for the angel ring, that is probably something on my end that I'll look into. 

A bandaid solution for productive views is browsing all the recipe categories. Once doing so it will generate the productive bee crafting recipes. Click on the crafting category when viewing any recipe to see them all 
. (It's those tabs on the very top of REI window)
