### ISSUE TITLE
[BUG] Inferium & Prosperity Ore not generating 

### ISSUE THREAD

**Issue by Ultraxite** [itsdinkd/AQM3#109]
**Modpack Version**
1.0.5
**Minecraft Version**
1.18.2
**Describe the bug**
On our server, we have not found a single prosperity or inferium ore in neither the end nor the nether. I have used commands to scan large swathes of chunks by using /fill x1 y1 z1 x2 y2 z2 air replace [inferium/prosperity ore for the relevant dimension], where the x and z values are dozens of chunks apart, creating a large sqaure, and the y value ranges from 10 to 50 as that is what the config suggests it should generate at. this creates a very large cuboid, and across numerous tests across many vanilla and non-vanilla biomes in both dimensions, across millions of scanned blocks, it has not once found a single ore. So either it is way way way too rare, or it is not generating for some reason. we have not touched the mystical agriculture or aggriditions configs, and they say the ore spawning is enabled. In addition, across the entire server with up to 8 people, many with high playtime and high tiers of looting/lots of mob killing in the nether and end, not a single inferium essence has dropped from the mobs. this has been the case afaik since we started the server in v1.0.2, but we didnt do serious nether/end exploration/mining till 1.0.4, and didnt do command analysing of terrain till 1.0.5. it makes it very difficult to progress and we cant even make stuff like the starter prefab farm, for example.

**To Reproduce**
No idea, just the way our server is?

**Expected behavior**
Probably should be at least a bit of inferium or prosperity ore generating.

**Screenshots**
cant screenshot what isnt there

**Crash log or latest.log.log**
no crash or error.

**Additional context**
N/A

**Comment by andyalex87** [comment]
Looking at the config for Mystical Agriculture it looks like the biome whitelist is empty which may be the cause of this issue.

**Comment by harmoncoffee** [comment]
Would like to see this fixed! :)

**Comment by chucktheviking** [comment]
Has anyone generated a BiomeWhitelist I could add to my server to allow these ores to spawn?

**Comment by chucktheviking** [comment]
Adding biomes to the Biome Whitelist and then exploring new chunks that have never been loaded does not generate inferium, prosperity, or soulstone.

**Comment by itsdinkd** [comment]
increased spawn rates in 1.6
