### ISSUE TITLE
crashing when i try to look at the recipe for framed dark oak planks and i cant find normal framed oak planks

### ISSUE THREAD

**Issue by yukichan274** [itsdinkd/AQM3#11]
i keep on crashing when i try to look at the recipe for framed dark oak planks and i cant find normal framed oak planks which is what is needed 

https://paste.corebot.dev/ifugiwukig.rb

**Comment by Houyami** [comment]
Adding my own log to further verify this. This is on the most recent version.
https://paste.corebot.dev/axufofoyuk.rb

**Comment by yukichan274** [comment]
so i just tried to put oak wood into 2 slots on Architects Cutter and the item showed up i was able to make it without crashing aswell but i have also found that trying to look at recipes for the Architects Cutter causes me to crash too 

mod is Domum Ornamentum

**Comment by itsdinkd** [comment]
Known bug with REI and Domum Ornamentum
