### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by madster456** [itsdinkd/AQM3#112]
**Modpack Version**
1.0.5
**Minecraft Version**
1.18.1
**Describe the bug**
This seems to be a duplication bug. When using drawers from the storage drawers mod, and having sticks in your hand. When you go to put the sticks in the drawer, they will all disappear from your inventory, but chat will say "Nobody owns this block". If you click in your inventory where the sticks were before, all the sticks in every slot of your inventory show back up. But the sticks inside the drawer remain. Effectively duping the sticks.

**To Reproduce**
1. Place drawer
2. Try and put sticks into drawer. I had several stacks.
3. Sticks will appear in drawer, and will _NOT_ show in inventory.
4. Right clicking the drawer with a slot selected that originally had sticks will display the "Nobody owns this block" message.
5. Go back into inventory, and left click on that inventory slot, all sticks show back up in inventory regardless of what is in drawer.

**Expected behavior**
Sticks move from my inventory, to the drawer. Instead they duplicate themselves.

**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by roykili** [comment]
try disable flan mods
