### ISSUE TITLE
[BUG]Not being able to put sticks into special crafting area

### ISSUE THREAD

**Issue by Siarc47** [itsdinkd/AQM3#113]
**Modpack Version**
1.0.5
**Minecraft Version**
1.18.2
**Describe the bug**
My friends and I cannot place sticks into special crafting blocks such as manaweaving altar in the mana and artifice mod and machine crafter. It cone up with nobody owns the block.

**To Reproduce**
First get a mana weaving altar from the modpack mana and artifice and then try right clicking it with sticks. This will lead to the error message "nobody owns this block"

**Expected behavior**
The stick will placed into the special crafting area allowing the ctaftinfbench to make the desired item.

**Screenshots**
![2022-07-13_20 32 15-1](https://user-images.githubusercontent.com/71032076/178811147-3f2d0c7f-cbd5-4f3b-90ff-91ae57e829b4.png)

**Additional context**
I don't think this is a bug but unexpected problems that came with multiple mods. I think it has something to do with supplementaries with adding sticks to the ground while having tiki sticks in the game which look similar.

**Comment by itsdinkd** [comment]
Thanks for reporting. I will change the debugging item for FLAN
