### ISSUE TITLE
[Bug] When near an Arch Maykr in the End

### ISSUE THREAD

**Issue by Chazito** [itsdinkd/AQM3#121]
Modpack Version: 1.0.6

Minecraft Version: 1.18.2

Well the problem seems to be mobs from MCDoom because I also have lag issues near other mobs that spawn in the End. The crash is when an Arch-Maykr spawns and lives, as soon as you see the boss bar in your screen that's a game over unless you have admin permissions to execute the /kill command.

1. Go to the End.
2. Go to any biome in the End except the dragon island
3. Find an Arch-Maykr
4. Server's TPS goes down and eventually crashes

The server crashes. There are not issues on the client, no FPS issues. Only the server dies.

Crash [log.](https://pastebin.com/Ks4PyGAM)

Server info:
Rented server on Akliz
6GB Ram

**Comment by itsdinkd** [comment]
Download the mcdoom update and use it to replace current version in aqm3. otherwise wait for aqm3 update
