### ISSUE TITLE
[BUG] Smelting end black opal ore yields amethyst

### ISSUE THREAD

**Issue by Uberspective** [itsdinkd/AQM3#126]
**Modpack Version**
1.0.6
**Minecraft Version**
1.18.2
**Describe the bug**
When you smelt black opal ore in a furnace or futurepack industrial furnace, you get amethysts instead of black opals.

**To Reproduce**
1. Get End Black Opal Ore.
2. Put it in a Furnace or Industrial Furnace with fuel.
3. Observe output.

**Expected behavior**
Black Opals are produced by smelting Black Opal Ore in a furnace.

**Comment by itsdinkd** [comment]
Yikes. bad bug. thanks for reporting

**Comment by V2LenKagamine** [comment]
Bug still exists in 1.1

**Comment by itsdinkd** [comment]
Forgot all about this, apologies for the super delayed effort. This is has been fixed in v1.7
