### ISSUE TITLE
[BUG] Tinkers Construct pickaxe does not interact properly with some mods

### ISSUE THREAD

**Issue by Eqlipse** [itsdinkd/AQM3#128]
**Modpack Version**
1.0.6
**Minecraft Version**
1.18.2
**Describe the bug**
Tinkers Construct pickaxe doesn't interact properly with blocks from certain mods, such as Stalwart Dungeons, or the Bygone Nether. More specifically, either the block will break, but not drop anything (such as with ALL Stalwart Dungeons blocks), or refuse to break at all, such as in the case of Withered Blackstone (all variants) or Withered Debris blocks from Bygone Nether.

I have not extensively tested if this issue persists with other mods in the pack.

**To Reproduce**
1. Go to any Stalwart Dungeons block, or Bygone Nether block.
2. Use any appropriate-level Tinker's Construct mining pick on the block.

**Expected behavior**
Block should leave a pickup-able item upon breaking. It will do so when using an appropriate vanilla mining pick.

**Comment by itsdinkd** [comment]
this is an issue unfortunately that would need to be fixed by either dev of either mod to make the two interactable.
