### ISSUE TITLE
[BUG] Server-Client pack Mod Discrepancy.

### ISSUE THREAD

**Issue by V2LenKagamine** [itsdinkd/AQM3#131]
**Modpack Version**
1.0.6
**Minecraft Version**
1.18.2
**Describe the bug**
Server-Client pack discrepancy.

**To Reproduce**
Download latest Client (1.0.6) pack and Server (1.0.6) pack from Curseforge
Attempt to join Server with Client pack downloaded
Note: Server states 3 mods missing:

craftingcraft-forge-1.18.2-12.0.0.jar
player_companions_1.18.2-1.1.0.jar
PlayerRevive_FORGE_v2.0.1_mc1.18.2.jar

**Expected behavior**
Server pack contains same mods as Curseforge "Client" modpack

**Suggested Solution**
Remove Craftingcraft & player companions from Server Pack
Add Player Revive to Client Pack

**Comment by itsdinkd** [comment]
You didnt download the correct server pack. you need 1.0.6hf
