### ISSUE TITLE
[BUG] Carry On + Villager Crash

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM3#132]
**Modpack Version**
1.0.6
**Minecraft Version**
1.18.2
**Describe the bug**
Picking up a villager with Carry On makes your player crash, and puts them in a soft ban state (Can't log back on until the mod is removed)

**To Reproduce**
1. pick up a villager with carry On
2. RIP 

**Expected behavior**
You should be able to pick up the villager with carry on without getting soft banned

**Crash log or latest.log.log**
https://gist.github.com/90f7de2bc7dfa82d75f8e0a405886848

Contact OhxSebby#3337 for more info

**Comment by PleahMaCaka** [comment]
I have the same problem, it doesn't end in crashing once, it keeps crashing

**Comment by Sebas-Re** [comment]
> I have the same problem, it doesn't end in crashing once, it keeps crashing

Temp workaround is to disable carryOn so you can join back into your world. You can re-enable it after

**Comment by itsdinkd** [comment]
blacklisted in 1.1.1
