### ISSUE TITLE
[BUG] Playerdata corrupts when looking at recipe from quest book

### ISSUE THREAD

**Issue by Cloudninjakip** [itsdinkd/AQM3#133]
**Modpack Version**
1,1
**Minecraft Version**
1.18.2
**Describe the bug**
Viewing the recipe of any item required for any quest corrupts playerdata
**To Reproduce**
1. open the quests
2. go into a quest that wants you to craft something
3. click on the thing it wants you to craft in that menu

**Expected behavior**

It should just not corrupt my playerdata

**Screenshots**

**Crash log or latest.log.log**
https://crashy.net/ip2Am7QEXwrzoEBZLtW8

**Additional context**
None

**Comment by V2LenKagamine** [comment]
Can confirm the error.

**Comment by jorygo** [comment]
I am also seeing this issue:
https://bytebin.lucko.me/7ogpAYeFRW

For more detail, the specific quest/action that is for is:
Humble Beginnings > Starting Out > How to Claim Land > Click on the golden hoe
