### ISSUE TITLE
[BUG] Invisible MCDoom mobs/items untextured, quests crashing clients, JEI not allowing recipe call to Refined Storage crafting

### ISSUE THREAD

**Issue by Nyomsuwu** [itsdinkd/AQM3#134]
Modpack Version
1.1

Minecraft Version
1.18.2

Describe the bug
Mobs and items for MCDoom are invisible/untextured, clicking on certain quest items in the quest book will crash client (as stated in previous report, just seconding it), JEI doesn't allow clicking of items from the recipe screen with the "+" to load into RS crafting table.

To Reproduce
- Load into the nether to see invisible mobs, try to use the gun crafting table to craft MCDoom equipment. 
- Quest book issues as stated in previous post. 
- Use RS crafting table, click the "+" on a recipe from JEI and it will not call the items from RS into the table

*Issues compiled from discord server*

**Comment by itsdinkd** [comment]
INvisible mobs fixed in 1.1.1


As for the other issues lets keep them separated individually since its not related. Can you open a new issue and provide the crash log for #2 


#3 would need to be reported to dev
