### ISSUE TITLE
Enigmatic Legacy "error during sided_setup event phase."

### ISSUE THREAD

**Issue by DruCart3456** [itsdinkd/AQM3#145]
On trying the modpack for the very first time, I got an error reading 

![image](https://user-images.githubusercontent.com/111559535/234453905-c5045ada-552d-4513-a52c-869ca0cece20.png)

Here's the latest.log, and the crash log. Any reason this might have happened? Or a way to fix it? I'm not sure what to type to help explain the situation; I only just installed the modpack on Curseforge, and opened it. I've not touched it before.

[latest.log](https://github.com/itsdinkd/AQM3/files/11328468/latest.log)

[crash-2023-04-25_22.43.44-fml.txt](https://github.com/itsdinkd/AQM3/files/11328471/crash-2023-04-25_22.43.44-fml.txt)

**Comment by DruCart3456** [comment]
I've also had another "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" crash when loading any shader whatsoever, as well as the Elevator mod cease to function on random boot ups. My PC could handle All the Mods, is this that much heavier??

Crash logs for the Shader crash as well. Sorry if they should be in their own post. All are caused on booting.

[crash-2023-04-26_00.59.57-client.txt](https://github.com/itsdinkd/AQM3/files/11329183/crash-2023-04-26_00.59.57-client.txt)

**Comment by LittleLyla** [comment]
I'm also having this exact issue where I cannot load up Enigmatic Legacy. Here is my crash log: https://pastebin.com/WgPQAxH3

**Comment by itsdinkd** [comment]
im unable to reproduce this so i cant really help.... unfortunately... you can delete enigmatic legacy if its causing issues to were you cannot launch.

**Comment by LittleLyla** [comment]
Strangely! I got it to launch. I have to not alt+tab while it's loading. Not sure why that makes a difference, but it's worth noting.
