### ISSUE TITLE
Missing multiple Mods mentioned in Pack description?

### ISSUE THREAD

**Issue by CrownJoker** [itsdinkd/AQM3#146]
As of AQM3-1.3, it appears that the mods below are not actually included in the pack, yet are still mentioned in the modpack description. Are these mods planned to be added, or is it just a mistake in the description?

Missing Mods:
Relics
Valhelsia Structures
Awesome Dungeons
Restored Earth
RevampedWolf
Instrumental Mobs
SlashBlade
TrapCraft

**Comment by CrownJoker** [comment]
Just for completeness, in case the description needs changing, here are the additional mods missing from the pack that are still mentioned on the 👉 list:
ValleyCraft
Occultism
Progressive Bosses
Castle in the Sky

**Comment by itsdinkd** [comment]
> Just for completeness, in case the description needs changing, here are the additional mods missing from the pack that are still mentioned on the 👉 list: ValleyCraft Occultism Progressive Bosses Castle in the Sky

These mods are in MC  1.18.1 version of aqm3

**Comment by itsdinkd** [comment]
though i am adding relics back cause I forgot all about it and it wasn't out when 1.18.2 came out.

**Comment by CrownJoker** [comment]
Hadn't realized there was a difference in the 1.18.1 and 1.18.2 packs, thanks!
If it's of any help, all the mods I had listed now seem to be available in 1.18.2
