### ISSUE TITLE
Attuned titanium is uncraftable

### ISSUE THREAD

**Issue by anga** [itsdinkd/AQM3#147]
Attuned titanium ingot crafting does not work.

JEI crafting is 1 pure titanium, 1 ender perl and 1 myst dust inside an electric purifier, but the purifiuer does not detect the crafting and never starts.

**Comment by ghost** [comment]
Not a bug, but a feature in Assembly Lines.
You will need a "Purifier Upgrade: Enhanced Filtering" to make the purifier able to process more recipes.

**Comment by anga** [comment]
Oh, sorry about that. Closing it
