### ISSUE TITLE
"Small Basalt Column" Structure causing server crash

### ISSUE THREAD

**Issue by CorgiZero** [itsdinkd/AQM3#149]
I'm moderating a server and for some reason whenever someone gets close to a structure called 'small basalt column' the server goes down. Additionally, the person who causes the crash tends to get stuck in a crashloop whenever it happens, bringing the server down each time they rejoin. Attached is the crashlog.

https://pastebin.com/p171J3Di

**Comment by itsdinkd** [comment]
Due to bygone nether. fixed in 1.4.4
