### ISSUE TITLE
Getting near to a "Mushroom Mine" freezes game

### ISSUE THREAD

**Issue by Seegras** [itsdinkd/AQM3#15]
Not entirely sure what happens here, but in singleplayer going near (10 chunks, activation distance) to a structure called "Mushroom Mine" freezes the game in a weird way, like a split-brain, between client and server. 
You can still move, but the mobs don't and you can break blocks, but they don't drop. You'd expect to rubberband back some time, only after 5mins waiting, it still didn't happen. Other structures do not appear to have that problem. 

You can change the frequency of them spawning in config/when-dungeons-arise-common.toml (for testing)., 

There are no errors in the logs. Nothing.

**Comment by itsdinkd** [comment]
Thats a new one. I will report this to dungeons arise. can you get the latest.log when this lag starts kicking in for me please? (server and client)

**Comment by itsdinkd** [comment]
Disabled in the mean time
