### ISSUE TITLE
"/bin/bash^M: bad interpreter: No such file or directory"

### ISSUE THREAD

**Issue by Ashrahl** [itsdinkd/AQM3#152]
I use Ubuntu Server for my Minecraft servers.  I encountered an error with the start script:
"/bin/bash^M: bad interpreter: No such file or directory"
It was related to the script being created with windows, and the line being different.  I ran a replace on the script and removed the bits.
sed -i -e 's/\r$//' startserver.sh

Link to relevant stackflow:  https://stackoverflow.com/questions/14219092/bash-script-bin-bashm-bad-interpreter-no-such-file-or-directory

**Comment by Ashrahl** [comment]
Oops, sorry.  It's for the AQM3 version 1.5's startserver.sh

**Comment by itsdinkd** [comment]
sorry for late reply. i will run this in ubuntu

**Comment by itsdinkd** [comment]
Fixed in 1.7
