### ISSUE TITLE
v1.5 Nether generation failing / causing crash on server

### ISSUE THREAD

**Issue by ImKringle** [itsdinkd/AQM3#154]
Ran into this on a server, and tested using a different seed on v1.5 of AQM3; When entering the Nether the logs are immediately spammed with a height index error and you fall until the server crashes or Singleplayer tries to catch up (floated on a ghost block in SP, nothing would render after the game teleported me back to portal height)

Logs:
https://mclo.gs/FEmL9wS

Removing Amplified Nether seemed to have allowed things to *kinda* load in, but it was still extremely sluggish

Tested on v1.5 / Windows 11 + a Linux server / 8GB RAM on both

**Comment by itsdinkd** [comment]
Fixed in 1.7 by removing infernal expansion
