### ISSUE TITLE
[v1.5] [Forge 4.2.7] Water evaporates when trying to place in overworld

### ISSUE THREAD

**Issue by Rhyssia** [itsdinkd/AQM3#155]
Using a water bucket will cause the water you attempted to place to evaporate instantly in the overworld.

Issue is tied to [Forge 4.2.7], updating and using [Forge 4.2.10] resolved the issue.

**Comment by MisterGrace** [comment]
Thank you for the heads up on it being forge related. :)

**Comment by itsdinkd** [comment]
updated in v1.7
