### ISSUE TITLE
[1.6.1] Unable to place water in Overworld

### ISSUE THREAD

**Issue by QuartzJoa** [itsdinkd/AQM3#159]
Hi, 

I've recently created a server for my friends and I and I've encountered a very annoying bug: we are unable to place water in the overworld, it evaporates like we are in the Nether. After a few google searches I found that the bug is caused by forge version 40.2.7 and by updating to 40.2.8 it fixes this bug. So is it possible to update the modpack with a newer version of Forge ?

Many thanks!

**Comment by itsdinkd** [comment]
updated in 1.7
