### ISSUE TITLE
Futurepack crashes when opening E-Scanner and stop working Industrial Neon Furnace

### ISSUE THREAD

**Issue by cabritelo** [itsdinkd/AQM3#164]
Hello Team,

Playing in a Private server. Last version of AQM3. I am the only one in my group following this Futurepack mod. 

Since few days/hours ago, I am having issues with Futurepack mod. I already am quite advanced into it (recently visited the first world Menelaus). I am not exactly sure if the problems started then. Opening the E-Scanner and clicking on any icon, the game crashes. I am in a private server where I have access to it (from a friend)
Another issue, there are few machines like Industrial Furnace and Industrial Neon Furnace that stop working suddenly too. (It has energy, and I have created a new couple of them)
I attach the crash report for the first scenario described above: https://gist.github.com/itsdinkd/a07d8771a3c52e2b0f51f0e59870e747

Thank you very much in advance

**Comment by cabritelo** [comment]
I discovered I have lost the knowledge of certain receipes like Aluminium plates with any (Neon) Industrial Furnaces, or even the Logic Chipset receip!
Game still crashes when I click any of the items discovered on E-Scanner

**Comment by itsdinkd** [comment]
Thank you for reporting. Unfortunately there is nothing I can do for this. This seems to be an issue with the mod itself, and that is something i have no control over. Your best bet would be to report this to the developer.
