### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by SamSprink** [itsdinkd/AQM3#17]
[00:31:03] [INFO] Starting Loader, output incoming
Error: Could not find or load main class @libraries.net.minecraftforge.forge.1.18.1-39.0.10.win_args.txt

**Comment by Aqual0n** [comment]
same issue here, any updates?

**Comment by Aqual0n** [comment]
If someone will search for answer here, you need to update your java to fix this.
I've installed this package and it started working.
https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe

**Comment by Darazzledazz** [comment]
download java 17 jdk

**Comment by itsdinkd** [comment]
> @itsdinkd same issue here, any updates?

This isn't used for support. You can find and ask for support in our discord
