### ISSUE TITLE
[BUG] [CONSTANT CRASH] Can`t open chest in one location

### ISSUE THREAD

**Issue by DamianBerek** [itsdinkd/AQM3#21]
Modpack Version 1.2.2a
Minecraft Version 1.18.1

something might be seriously broken with aqm3. you know those bits of obsidian portal on netherrack which spawn in overworld ? so every time i get to one, all is good until i try to access chest on it. as soon as i try to open chest nothing happens literally. chest dont get opening animation inventory dont show up etc and if i try to place any block and then use pickaxe to take it back the blok vanish and server crash every time. however if i dont do anything after trying to interact with chest server runs for max 30 sec then crash

To reproduce follow above description
Expected behaviour : i can open chest, can place and pick up block, and server/game wont crash
attached few crash logs
[serverXrashLogs - 11 Jan 2022 10_56_7.zip](https://github.com/itsdinkd/AQM3/files/7845918/serverXrashLogs.-.11.Jan.2022.10_56_7.zip)

**Comment by DamianBerek** [comment]
i tried to reproduce it in single player same thing happened tho game didntt crash chest reapeared and opened after some time. seems like it happen on server mostly

**Comment by itsdinkd** [comment]
Please record a video
