### ISSUE TITLE
[BUG] Can't enter compact machine

### ISSUE THREAD

**Issue by Seegras** [itsdinkd/AQM3#24]
**Modpack Version** 1.3.2

**Minecraft Version** 1.18.1

**Describe the bug**
Right-clicking on a compact machine with the personal shrinking device does nothing. It's not even registered, new compact machines will not given an ID. 

**Additional context**
Also: Breaking the compact machine duplicates it. If it already has an ID, it will keep it and thus the inside will be the same compact machine. But if it hasn't it's of course possible to duplicate it.

**Comment by itsdinkd** [comment]
Does this occur in 1.3.3?

**Comment by Seegras** [comment]
It does, when you use the old save. Only starting a new games will make it work.

**Comment by itsdinkd** [comment]
Gotcha. nothing I can do about this unfortunately.
