### ISSUE TITLE
beyond earth world height issues

### ISSUE THREAD

**Issue by nocturnalfoxboi** [itsdinkd/AQM3#26]
1.3.3

1.18.1

tier 1 rocket kicks you out at world height in survival no matter what you do but will work in creative

1. get in a tier 1 rocket that is fueled
2. press space in survival
3. wait for it to hit world height
4. observe the ship disappearing and you plummeting back to your death

i expect it to go past world height and put me in the planet choosing screen

**Screenshots**

**Comment by MrSheen123** [comment]
This is in relation to issue #40 on Beyond Earth's Github. Unsure if there is a workaround until the dev fixes it but it caused a lot of confusion with people on my server haha

[https://github.com/MrScautHD/Beyond-Earth/issues/40](url)

**Comment by MrSheen123** [comment]
Mod developer has closed the issue stating it is not their problem

https://github.com/MrScautHD/Beyond-Earth/issues/40

**Comment by itsdinkd** [comment]
Try doing what I mentioned in that issue in the latest comment. If that doesn't fix it then it's something else, if it does fix it and the rocket stays but server/game crashes, then it's definitely his mod.

**Comment by MrSheen123** [comment]
I will get that set and let you know the results! Thank you

**Comment by MrSheen123** [comment]
I ran the server with that but it still does not work. However, when I get kicked out of the rocket I get the "moved too quickly!" log in the server where I didn't before and it appears as soon as I get kicked out so looks to be related.

**Comment by MrSheen123** [comment]
Found a workaround, build a platform near player height and you can get build a rocket platform there that makes it to the world selection screen before player moved too quickly kicks in

**Comment by itsdinkd** [comment]
Beyond Earth removed on 1.3.4
