### ISSUE TITLE
[BUG] Silent Gear fishing rods do not cast.

### ISSUE THREAD

**Issue by TaRippa** [itsdinkd/AQM3#27]
**Modpack Version**
v1.3.3
**Minecraft Version**
1.18.1
**Describe the bug**
When attempting to cast a silent gear fishing rod, the hook entity will be spawned but then is promptly removed resulting in not being able to cast the rod.

**To Reproduce**
1. Craft Silent Gear fishing rod.
2. Right click to cast fishing rod.
3. Observe deletion of hook entity.

**Expected behavior**
Rod should be casted as per normal Minecraft fishing rod.

**Screenshots**

**Crash log or latest.log.log**
No Crash log but link to known issue pages on Silent's github:

https://github.com/SilentChaos512/Silent-Gear/issues/476

https://github.com/SilentChaos512/Silent-Gear/issues/425

**Additional context**
Known problem for silent. Server specific - will just need to change setting server side I believe.

**Comment by itsdinkd** [comment]
This was a bug with Silent Gear. in their latest update, they have fixed it.
