### ISSUE TITLE
[BUG] Can't place Glowing Water - Hyper Lighting

### ISSUE THREAD

**Issue by z0rkie** [itsdinkd/AQM3#28]
Running a Private Server on v.1.3.3 of AQM3

Minecraft v.1.18.1

When you scoop up a bucketfull of glowing water, no matter the color (tested 3 so far) you can't place it back in to the world.

**To Reproduce**
1. Scoop glowing water in to bucket
2. Right click anywhere
3. Notice nothing is happening
4. Realize you can't place it anywhere
5. Sulk and cry because now you have to use another way to light up the darkness.

**Expected behavior**
Water to go from bucket in to sourceblock.

**Screenshots**
Not needed

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

No crash or logfile

**Additional context**
It's not gamebreaking, just makes me sad.

**Comment by hypherionmc** [comment]
Just a heads up, this issue has been reported to me and I am aware of it. It's some kind of weird conflict with REI. I am in contact with the dev of REI to figure out why this happens

Ref: [#5](https://github.com/Exploding-Creeper/Hyper-Lighting/issues/5)
