### ISSUE TITLE
[Crash] Buddycard Power meter and Medal

### ISSUE THREAD

**Issue by OriginalHust** [itsdinkd/AQM3#29]
**Modpack Version**
1.3.3

**Minecraft Version**
1.18.1

**Describe the bug**
In multiplayer, using the power meter or the buddy medal from the mod "Buddycards Core" crashes the server.

**To Reproduce**
Right click to use the power meter or buddy medal.

**Expected behavior**
Using either item is suppose to check your collection then tell you your completion rate for the power meter, or enchant the buddy medal based on completed sets.

**Crash log or latest.log.log**
Crash logs from power meter use:
https://paste.corebot.dev/imapefojup.rb
https://paste.corebot.dev/cabayojixi.rb

Crash logs from buddy medal use:
https://paste.corebot.dev/uhadefumuz.rb
https://paste.corebot.dev/otiyadavuq.cs

**Comment by itsdinkd** [comment]
Please test on 1.3.4 when released and let me know if it exists

**Comment by itsdinkd** [comment]
Assuming it works now as I did not receive a response
