### ISSUE TITLE
[BUG] Server Crash, probably forge version related

### ISSUE THREAD

**Issue by HammerDave** [itsdinkd/AQM3#31]
**Modpack Version**
1.3.3
**Minecraft Version**
1.18.1

**Describe the bug**
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.stal111.valhelsia_structures.common.block.entity.JarBlockEntity.save(net.minecraft.nbt.CompoundTag)'

According to a bug report on valhelsia structures, this is a problem with mods which are using methods that were
deprecated in forge >= .45 so we are trying to downlevel forge on the server (.45) to match what is in the client (.22).

**To Reproduce**
1. Run on  server
2. Approach a valhelsia structure (not sure exactly which one(s) this is triggered by)
3. Server crashes

**Expected behavior**
No crash.

**Screenshots**

**Crash log or latest.log.log**
Key line pasted above, log available on request.

**Additional context**
https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/119

**Comment by itsdinkd** [comment]
The server start Downloader is set to download what's in the modpack (I
might be wrong and this might be only aqm2) but if so, it should only be on
.22?
