### ISSUE TITLE
[BUG] Game kicking me from the official server if i'm crafting certain recipes

### ISSUE THREAD

**Issue by denehelmbach** [itsdinkd/AQM3#32]
**Modpack Version**
v1.3.3
**Minecraft Version**
1.18.1
**Describe the bug**
If trying to paste certain recipes (happened with the wooden crate from "Better Crates") the REI browser into a crafting table (also tried to use the mobile crafting table) i get kicked from the server with the following error message:
Internal Exception: io.netty.handler.codecDecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

**To Reproduce**
1. Use any crafting grid
2. Paste a recipe with the REI recipe browser by Shift+Left Clicking on the plus sign (For me the wooden crate recipe crashed to 100%)
3. The server should kick your with my stated error message

**Expected behavior**
The recipe should be pasted into the crafting grid and you would be able to make your crafting recipe with no problem.

**Screenshots**
![problem1](https://user-images.githubusercontent.com/57114163/150817425-0486f294-f1f9-4af5-8758-e11a1b0551ed.png)

**Crash log or latest.log.log**
[latest.log](https://github.com/itsdinkd/AQM3/files/7926879/latest.log)

**Comment by itsdinkd** [comment]
This has been reported to REI a while back, looks like it still has yet to be fixed on their end.
