### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by demon29292** [itsdinkd/AQM3#35]
**Modpack Version**
1.3.3
**Minecraft Version**
1.18.1
**Describe the bug**
the game crashed instantly 
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/98810427/151948465-be40374c-3792-49c3-a461-2c64e4c1be0a.png)

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by itsdinkd** [comment]
Why did you not fill out the rest of the ticket? you only put 4 words and a screenshot that tells me nothing. Closing until filled out properly, and a title added.

**Comment by demon29292** [comment]
sorry
