### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rozenkai** [itsdinkd/AQM3#36]
Was Wondering If The New Update Could Have Some Railway Mods 
Such As Minecraft Transit Railway or something with more functional rails
and since we already have a crayfish mod maybe Ultimate Car Mod 
thanks and one day we will get banked rails track hopping and loop rails and i shall build the ultimate runaway minecart

**Comment by itsdinkd** [comment]
Sorry but that will be too random for the modpack and much of an edge case of usage.
