### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Oshawott98** [itsdinkd/AQM3#37]
**Modpack Version**
1.3.3
**Minecraft Version**
1.18.1
**Describe the bug**
A clear and concise description of what the bug is
.Good evening, I tried to use the modpack another quality 3 of minecraft. I keep going at 2 fps, the other modpacks I go quietly at 120 fps. What should I do? Thank you

**Comment by itsdinkd** [comment]
Already discussed on discord. Also, [BUG] is not a correct title for a issue, next time please put in a proper title after the [bug] prefix
