### ISSUE TITLE
[BUG] LAN - connection lost

### ISSUE THREAD

**Issue by biwman** [itsdinkd/AQM3#38]
**Modpack Version**
Another Quality Modpack 3 - 1.18.1 
**Minecraft Version**
1.18.1
**Describe the bug**
I have 2 PCs with Minecraft 1.18.1 in the same LAN network.
Wehn I createa  world with AQM3 on 1 PC and open it for LAN, then on another PC I can see the local server and join it but while loading the contact (at terrain loaind step) I got message "connection lost".
I dont have this issue when I join official server or when I play with no mods or when I play some other modpacks - this issue happens only when I try AQM3

**To Reproduce**
Well.. Click on 1 PC: Open LAn, and on another PC - Multiplayer-> join server on the list (it appears with no problems)

**Expected behavior**
Joining the worlds.

**Screenshots**
Nothing to attach - the error is just "connection lost".

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*
I dont know where to find logs. Are there any in such case?

**Comment by Shadowner83** [comment]
Could either be a firewall issue or specific mod issue.

The logs can be found in the logs folder of your minecraft installation.
