### ISSUE TITLE
[BUG] Game crashes before loading fully

### ISSUE THREAD

**Issue by TheCatMan2000** [itsdinkd/AQM3#43]
**Modpack Version**
v1.4.2

**Minecraft Version**
1.18.1

**Crash log or latest.log.log**
[hs_err_pid14680.log](https://github.com/itsdinkd/AQM3/files/8052527/hs_err_pid14680.log)
https://paste.ee/p/V2gZ9

**Additional context**
Using MultiMC.

**Comment by itsdinkd** [comment]
This is a bug with MultiMC and should be handled as such

**Comment by Cypress187** [comment]
![2022-03-17_15 14 58](https://user-images.githubusercontent.com/11806774/158826227-539ca04d-8f60-4c0e-affc-40b8d9481c78.png)

**Comment by itsdinkd** [comment]
You are really behind on modpack versions. This error doesn't exist in more recent versions.
