### ISSUE TITLE
[BUG]Caged Mobs doesn't work

### ISSUE THREAD

**Issue by z0rkie** [itsdinkd/AQM3#44]
v. 1.4a

1.18.1

**Describe the bug**
Caged Mobs cages don't drop anything.

**To Reproduce**
Plop down either hopper cage or basic cage, throw in mob dna and ground watch it grow, pop and nothing drops in chest or inventory when clicked.

**Expected behavior**
Mob drops

**Screenshots**
None

**Crash log or latest.log.log**
None

**Comment by itsdinkd** [comment]
This is known and still waiting for the developer to fix it. closing since known.
