### ISSUE TITLE
[BUG] Crashing when using special arrows with End Bow

### ISSUE THREAD

**Issue by TehJams** [itsdinkd/AQM3#45]
**Modpack Version**
1.4.2
**Minecraft Version**
1.18.1
**Describe the bug**
Crashing sometimes when arrows are fired. I was using an End Bow with Punch 1, Power 3, and Soul Stealer. The arrows are Uncraftable Tipped Arrow - Instant Damage II.

This seems to happen when I am using many arrows in a confined location, particularly when I was fighting the Wither in a small room. I'm wondering if it is due to the particle effect of the arrow. 

**Crash log or latest.log.log**
https://paste.corebot.dev/ihuvedegav.php

**Comment by itsdinkd** [comment]
Please fill out steps to reproduce or provide more details, as well as a title to this ticket. 

What arrows? What bow? Was the bow enchanted?

**Comment by TehJams** [comment]
Sorry, I thought you might be able to tell by the crash log. I updated the post with some more information.

**Comment by TehJams** [comment]
This crash just occurred while I was fighting an infernal skeleton. I did not fire a single arrow at him. Just his arrows were involved in this. https://paste.corebot.dev/hasibuvaji.php

**Comment by itsdinkd** [comment]
Can you send me the latest.log when you crash? if this still happens on later versions of aqm3
