### ISSUE TITLE
[BUG] Its The Little Thinks / TkLib Crash

### ISSUE THREAD

**Issue by YannikSc** [itsdinkd/AQM3#46]
**Modpack Version**

v1.5.1

**Minecraft Version**

1.18.1

**Describe the bug**

- Launching a plain, unmodified installation causes a crash related to itlt
- Disabling itlt causes a forge loading error related to supercircuitmaker requires tklib 0.0.8 (but 0.0.4 is installed)
  - Updating tklib fixes the issue

I'm wondering if its only me or if others are experiencing those issues as well.

**To Reproduce**

1. Use the MultiMC Launcher to download the modpack
2. Run it
3. ?
4. Profit

**Expected behavior**

No crash

**Crash log or latest.log.log**

- itlt crash: https://pastebin.com/DQ0LuPC7

**Comment by MintyGold** [comment]
I can confirm the same happening to me with the same crash related to having the wrong version of tklib.

**Comment by itsdinkd** [comment]
Already known and reported to MultiMc. It's an issue with itit supposedly
