### ISSUE TITLE
[BUG] Supplementary Wall Lanterns can no longer be placed

### ISSUE THREAD

**Issue by PvtMcBagel** [itsdinkd/AQM3#50]
**Modpack Version**
1.5.3
**Minecraft Version**
1.18.1
**Describe the bug**
Wall Lanterns can no longer be placed. Right clicking on a wall with a vanilla lantern in previous versions would place a wall lantern from the supplementaries mod. This would work with vanilla lanterns, and lanterns from other mods.

We started the server on 1.4.2, updated to 1.5.1, and during that time Wall Lanterns worked correctly. We updated to 1.5.3 directly from 1.5.1, where supplementaries was updated.

**To Reproduce**
Easiest way is to load a superflat creative world and try placing a lantern on a dirt wall. I've confirmed that the configs for the supplementaries mod are exactly as AQM3 shipped.

**Expected behavior**

**Screenshots**
Wall Lantern from world that was created Pre-1.5.3
![image](https://user-images.githubusercontent.com/14795454/155578198-a3a8f184-4e88-4377-a528-ce50ed946c5d.png)

**Crash log or latest.log.log**
No crashing

**Additional context**
N/A

**Comment by itsdinkd** [comment]
Have you reported this to Supplementaries?

**Comment by PvtMcBagel** [comment]
I have not, I didn't know if it was an issue with the modpack or the mod itself.
