### ISSUE TITLE
[BUG] Mystical Agriculture Gobber End Globette Essence has no recipe

### ISSUE THREAD

**Issue by CornOnTheCaleb** [itsdinkd/AQM3#52]
**Modpack Version**
1.6

**Minecraft Version**
1.18.1

**Describe the bug**
Gobber End Globette Essence (id: mysticalagriculture:globette_end_essence) has no recipe to create a resource. It can be farmed from Gobber End Globette Seeds, but has no use of its own. Based on how other Mystical Agriculture essence is used, there likely should be a recipe using Gobber End Globette Essence to craft Gobber End Globette.

**To Reproduce**
1. Go to REI
2. Search for "Gobber End Globette Essence"
3. Hover over the item and press 'U' to view recipes
4. Nothing shows up, and no amount of messing around with the crafting table seems to result in a recipe

**Expected behavior**
Gobber End Globette Essence can be crafted into Gobber End Globette.

**Comment by itsdinkd** [comment]
Ah thank you for writing this. I forgot about it from our discord convo.

**Comment by itsdinkd** [comment]
Closing due to old version, and also fixed.
