### ISSUE TITLE
[CRASH] Cannot load game, mods failing to load

### ISSUE THREAD

**Issue by TehJams** [itsdinkd/AQM3#55]
**Modpack Version** 1.7

**Minecraft Version** 1.18.1

**Describe the bug**
Game crashes every time.

**To Reproduce**
1. Launch the game

**Crash log or latest.log.log**
[*crash log*](https://paste.corebot.dev/tigimiqiwi.pl)

**Additional context**
I have tried reinstalling the entire modpack as well as reinstalling minecraft.

**Comment by TehJams** [comment]
Tried removing the two mods and then I get this crash instead https://paste.corebot.dev/icoxipalal.pl

**Comment by itsdinkd** [comment]
Something is wrong with Entangled mod, and it's config? It says not enough data for the config. Try deleting the entangled config, I believe it's under server scripts in world folder

**Comment by itsdinkd** [comment]
Closing due to no response/update
