### ISSUE TITLE
[BUG] Mod Issue Involving Ladders

### ISSUE THREAD

**Issue by ElBrak** [itsdinkd/AQM3#56]
A user on my server build some ladders from Speedy Ladders and noticed that they could only climb the stone ladder only slowly, and could not climb the Iron Ladder at all. I investigated and found that the Gold and Diamond Ladder were impossible to climb as well. But you could descend them. I also noticed that while you could climb normal ladders the speed was slower than vanilla. I attempted to find mods that might affect ladder usage and disabled Quark, but this did not fix the issue. I loaded a Minecraft instance using only Speedy Ladders and they worked as normal. I believe there is a mod in the pack that is trying to force the player to always descend the ladder or something similar.

**Comment by itsdinkd** [comment]
Next time when you open a issue use the template provided when opening a Bug Report issue. I need to know the modpack version.

**Comment by ElBrak** [comment]
1.7 is the modpack version
