### ISSUE TITLE
[BUG] Payload error moving ingredients using (+)

### ISSUE THREAD

**Issue by instinxx** [itsdinkd/AQM3#57]
**Modpack Version**
AQM3 V 1.7

**Minecraft Version**
MC 1.18.1

**Describe the bug**
When clicking the '+' to move ingredients for certain recipes, (Minecraft Campfire in this case) the client crashes with "Internal Exception: io.netty.handler.codec.DecoderException: Java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes" (Screenshot attached)

**To Reproduce**
1. Open Crafting table
2. Search for "Campfire"
3. Select Campfire
4. Click the + Crafting table to move ingredients
5. Crash with Payload error as described above

**Expected behavior**
Ingredients move to Crafting grid and outputs a campfire

**Screenshots**
![image](https://user-images.githubusercontent.com/1753699/157469189-58417c48-0eb5-41da-9e97-1cf1221458a7.png)
![image](https://user-images.githubusercontent.com/1753699/157472204-8f28951a-7cc2-45c9-8661-5d5b10c773c2.png)
![image](https://user-images.githubusercontent.com/1753699/157472387-1a7222ab-28e2-43a5-b7a4-6adc2d8cd4fd.png)

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*
https://pastebin.com/yx3W7vAr

**Additional context**

**Comment by itsdinkd** [comment]
I've reported this to the REI dev a while back and unfortunately there
hasn't been a fix yet.
