### ISSUE TITLE
[BUG] Difficulty doesn't decrease properly on death, datapacks to fix dont work

### ISSUE THREAD

**Issue by Matthbo** [itsdinkd/AQM3#61]
**Modpack Version**
1.7

**Minecraft Version**
1.18.1

**Describe the bug**
The difficulty of a player goes down by -0.01 on death, which is basically nothing and very unbalanced.
Creating a datapack to change the behaviour of ScalingHealth doesn't work because the behaviour is being overridden by something.

**To Reproduce**
1. Get some difficulty in survival or creative (using cursed hearts)
2. Get killed (By mob, suicide or `/kill <username>`)
3. See if the difficulty went down with the SH meter or in chat
4. Add this datapack to the world (which is confirmed to change the behaviour in the mod outside of the modpack) 
[sh_mech_change.zip](https://github.com/itsdinkd/AQM3/files/8293809/sh_mech_change.zip)
5. Follow step 2 & 3 again
6. See that the behaviour is still being overridden by something

**Expected behavior**
The player's difficulty should be reduced a little when the player dies.
Datapacks to change ScalingHealth's behaviour shouldn't be overridden, this would give the player a chance to customize a little.

**Screenshots**
![2022-03-18_00 10 18](https://user-images.githubusercontent.com/4380412/158908870-e7aaf873-b6cf-4e88-83eb-42b232ba7382.png)
![2022-03-18_00 10 56](https://user-images.githubusercontent.com/4380412/158908885-41783879-d514-47a9-9495-abba38a2248c.png)

**Crash log or latest.log.log**
(Not really relevant, don't think it logged anything about this)
https://paste.ee/p/ykqtr

**Additional context**
There seems to be a mod or something changing the behaviour of ScalingHealth, which would be fine if it worked correctly and was balanced. But now the difficulty doesnt go down on death which in my eyes is very unbalanced and creating a datapack for the mod (which they want you to do) to change the behaviour not working seems like a big problem.

**Comment by itsdinkd** [comment]
Difficulty is not based on the default setting. Dying reduces by 0.01 hence you not seeing the change on the meter which goes off of whole numbers. I use my own datapack for the mod. 

Not a bug.

**Comment by Matthbo** [comment]
I don't see how reducing the difficulty of a player by 0.01 is even seen as a reduction.
It really doesn't make a difference even if the player died a 100x times, the difficulty would go up faster then you could reduce it.

Also creating my own datapack to change it since I can't do it via a config and it **not** working seems very much like a bug.
