### ISSUE TITLE
[BUG] Inventory Tool Tip hidden behind REI interface

### ISSUE THREAD

**Issue by Zeinath** [itsdinkd/AQM3#62]
**Modpack Version**

AQM-1.7-Forge

**Minecraft Version**

1.18.1

**Describe the bug**

When hovering over an item in the inventory, it's tool tip is hidden behind any REI interface that may be near it, making it nearly impossible to read.

**To Reproduce**
1. Open inventory
2. Hover over item in inventory with tool tip large enough to overlap with REI's interface
3. Have seriously difficulty reading the tool tip as it's mostly covered by REI icon's for recipes
4. Be frustrated

**Expected behavior**

Tool tip should appear clearly over any other UI element. When hovering over items in REI, tool tips display as expected, only seems to happen when hovering over items in the inventory.

**Screenshots**

Example screen shot can be seen on the Discord in the #aqm3-support-chat by Zeinath at 9:26am on 3/18/22.

**Crash log or latest.log.log**

Not a crash.

**Additional context**

Discussed with people in the AQM3 Support channel on the Discord, not the only one having the issue. Did a full reinstall of the client, issue persisted.

**Comment by Inyaahead** [comment]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/1348057/159592420-cc06c58e-c4fa-42d4-9135-962fd51c3c51.png">

**Comment by itsdinkd** [comment]
What color is your search bar

**Comment by Inyaahead** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1348057/159596686-19f32802-d976-4b94-a79b-e1e3543bd91b.png">

**Comment by Shadowner83** [comment]
Change the GUI Scale to AUTO and restart.

It solved it for me.

**Comment by itsdinkd** [comment]
> 

Your slot is locked. Ctrl a I believe while hovering, let's keep these questions in discord though. 

Your issue is due to cache recipes being enabled
