### ISSUE TITLE
Stacking Four Enchanted Books DCs Me From Server

### ISSUE THREAD

**Issue by DirtyBlondeMedic** [itsdinkd/AQM3#64]
Modpack Version: 1.7

Minecraft Version: 1.18.1

What Happened and How to Recreate:
I was in my base, micromanaging chest space when I noticed that you could place enchanted books on the floor. So I placed down 4 enchanted books on the same tile, 3 of which I believe were Corail Tombstone enchantments (if that matters) and they stacked on top of each other visually. A second later, I was disconnected from my server, and now I can't join back without it instantly disconnecting me again and saying "Saving world". I have even tried restarting the server entirely, and that didn't work either.

This is the crash log I've taken from it. Any help would be appreciated!
[crash-2022-03-21_23.22.13-client.txt](https://github.com/itsdinkd/AQM3/files/8320790/crash-2022-03-21_23.22.13-client.txt)

**Comment by itsdinkd** [comment]
Known issue and is fixed in 1.8
