### ISSUE TITLE
[BUG] Becoming invulnerable

### ISSUE THREAD

**Issue by Zuurio** [itsdinkd/AQM3#66]
**Modpack Version**
1.7

**Minecraft Version**
1.18.1

I became invulnerable. Mobs ignored me and I didn't take any dmg. Even the kill command didn't kill me, it just teleported me to the sky at my spawnpoint. Dying in the void didn't work either it just spawned me to the nether for some reason.

I fixed it by going into my playerdata with NBT Explorer and replacing 1 with 0 in the invulnerable setting. I don't have any idea why it got changed but that fixed it without losing any data.

**Comment by Zuurio** [comment]
![fix](https://user-images.githubusercontent.com/16821720/159728161-d7fb86bf-39b6-47ed-b05a-3d053b5dfd76.png)
The setting in the playerdata

**Comment by itsdinkd** [comment]
Duplicate of #58
