### ISSUE TITLE
[BUG] Mahou tsukai kills players using it

### ISSUE THREAD

**Issue by RealMegabear** [itsdinkd/AQM3#67]
**Modpack Version**
 Another quality modpack 3 version 1.7
**Minecraft Version**
 1.18.1
**Describe the bug**
Every time you use mana from the Mahou Tsukai mod you take damage, with 10 armor bars you take 0.8 damage for every 1 mana you use. So enything above 100 mana kills the player instantly even if you have the required mana. Even if this is intented, it makes magic like throwing a weapon in the lake nearly impossible since you take 7800 damage. Also things like automation is impossible since it just slowly kills the player over and over again. 

I tried to find ways arround it like with damage absorbion together with the Mahou tsukai discord but everything we came up with failed in the long run. 

**To Reproduce**
Try any spell or store your mana in a gem and take damage.

**Expected behavior**
Taking damage from every Mahou tsukai mana cost.

**Additional context**
An easy solution would be to disable the take damage while using mana part in the config so that the mod can be used again without having to die over and over again.

**Comment by itsdinkd** [comment]
Already known

**Comment by RealMegabear** [comment]
Will it ever be fixed on the official server then?
