### ISSUE TITLE
[BUG] Crash when placing Create Schematic that sampled wired Immersive Engineering Connectors

### ISSUE THREAD

**Issue by TeoNikolov** [itsdinkd/AQM3#69]
**Modpack Version**
AQM-1.7

**Minecraft Version**
1.18.1

**Describe the bug**
The client crashes when placing a Create Schematic which has sampled a set of blocks that include wired Immersive Engineering connectors.

**To Reproduce**
1. Connect to a hosted server (not tested on localhost/client).
2. Place two Immersive Engineering Connectors (I used low voltage or LV Connectors).
3. Craft and use a Create "Schematic and Quill" on the IE wired connectors. Save the schematic,
4. Create a Create Schematic and use a Create Schematic Table to load the saved schematic from Step 2 into the crafted schematic item.
5. Right click in the world with the saved schematic to try and place the schematic. The client SHOULD crash to a "Saving World" message.

**Expected behavior**
The client does not crash when placing the schematic.

**Screenshots**
- unable to do atm

**Crash log or latest.log.log**
[link](https://pastebin.com/4kCwqJQL)

**Additional context**
Line 9 of the crashlog indicates a call to immersive engineering. I re-tested the schematic by disconnecting the wires and re-doing the whole process outlined above. I was able to place schematics without crashing.

My suspicion is that the modpack devs can't do anything about this. The issue is probably related to some special way of handling connections in Immersive Engineering which Create does not account for. It is likely an issue that needs to be solved between the mod devs (probably IE since they seem to have their own system for handling connections). Then again, I haven't touched MC modding in 10+ years so I'm leaving it to the modpack devs to investigate and raise up the chain if necessary.

**Comment by itsdinkd** [comment]
We do not support older versions of aqm3
