### ISSUE TITLE
Alex's Mobs advancement crashing client

### ISSUE THREAD

**Issue by Houyami** [itsdinkd/AQM3#7]
https://crashy.net/ZHqNEg9vcK4Vi6xW2fqJ
Crashes upon clicking the tab.

**Comment by red2blue** [comment]
Looks to be due to BetterAdvancements

**Comment by red2blue** [comment]
whats the advancement name so i can clear it

**Comment by Houyami** [comment]
It's just the general tab.

**Comment by itsdinkd** [comment]
Can you get me the real crash log? not this crashy shit. NEC sucks for adding that. (no offense to you)
