### ISSUE TITLE
issue with better than lama's mod

### ISSUE THREAD

**Issue by Volos98** [itsdinkd/AQM3#71]
Another Quality Modpack 3 v1.8

Minecraft Version

1.18.1

Describe the bug

the game will launch just fine then when its about to finish it gives me a crash report and when clicking on the link it tells me that the mod couldn't load properly, when removing the mod it works but then cant join any servers.

To Reproduce

just launch the game and while its loading it pops up with the crash report

Expected behavior

i reckon it should work normally and not crash

Screenshots

Crash log or latest.log.log
Use pastebin.com to generate a link

https://bytebin.lucko.me/g34nt88GuY

Additional context

**Comment by Volos98** [comment]
realized i messed up the format so ill update it with the info you need

**Comment by ScreX56** [comment]
Same problem here made a report didn't realize it was already a report. #72 was my report saying the same thing

**Comment by Volos98** [comment]
> Same problem here made a report didn't realize it was already a report. #72 was my report saying the same thing

so i figured it out, in their discord it states that its an April fools joke even though its dumb af but all you gotta do is either wait till tomorrow or change your pc date to the 2nd and it will be fine i already did it and can confirm that it works
