### ISSUE TITLE
[BUG] Crash when loading save world.

### ISSUE THREAD

**Issue by ScreX56** [itsdinkd/AQM3#72]
**1,8**

**1.18.x**

**Crash when joining single player save world.**
A clear and concise description of what the bug is: game launches normally, click single player, click my saved world, loads until 100% then shows crash error and sends me back to the menu screen

**To Reproduce**
1. Go to 'single player'
2. Click on 'saved game'
3. Scroll down to 'N/A'
4. See error: after loading to 100%

**Expected behavior**

**Screenshots**

**Crash log or latest.log.log**
[*Use pastebin.com to generate a link*]
(https://bytebin.lucko.me/YIj5IAieK1)

**Additional context**
not much else to day, worked normal yesterday and  stopped working today, complete random.

**Comment by itsdinkd** [comment]
Yep this is known. The dev messed it up for everyone, remove the mod for now or set your PC clock to tomorrow.
