### ISSUE TITLE
[BUG] Productive Bees crash on showing recipe with JEI

### ISSUE THREAD

**Issue by MrHemanik** [itsdinkd/AQM3#74]
**Modpack Version**
1.8
**Minecraft Version**
1.18.1
**Describe the bug**
When trying to look up the breeding recipes for Productive Bees, the game will crash.

**To Reproduce**
1. Open your inventory
2. Search in JEI for a bee that is used for breeding (eg.: Skeletal Bee)
4. Press the key to open crafting recipes (default U)
5. See error (crashes with the possibility to go back to the main menu)

**Expected behavior**
JEI should normally open the breeding recipes for bees.

**Screenshots**
Before pressing U: https://i.imgur.com/B09dHLO.png
After pressing U:    https://i.imgur.com/gLWw9er.png

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*
https://pastebin.com/Sqf5ca5E

**Additional context**
No other mods were installed and no keys were rebound.
Tried in single- and multiplayer. Crashes either way. A friend tried to reproduce but he doesn't have that problem.
Tried restarting but the bug stays.
Reinstalled and restarted my computer, which fixed the bug EDIT: after restarting, but is still there, another friend and original mentioned friend who didn't have this bug had this bug now too.

**Comment by itsdinkd** [comment]
You should report this to JEI, not sure why you are posting it here. 1.8 uses REI
