### ISSUE TITLE
[BUG] Doom mod Spawns out of control

### ISSUE THREAD

**Issue by NegativeVolume** [itsdinkd/AQM3#75]
**Modpack Version**
v1.8
**Minecraft Version**
1.18.1
**Describe the bug**
The doom mod in the End dimension and nether is out of control, too many are spawning and bosses are spawning randomly and aggro-ing outside their render distance while slowing the server I'm on

**To Reproduce**
1. Go to Nether or End
2. Fight and Explore
3. Slowly experience lag
4. Constant Stutter issues

**Expected behavior**
Boss mobs  from the doom mod, spawn within their structures, not in the open, without lag. Boss should not aggro when not rendered.

**Crash log or latest.log.log**
none that can be generated when forced to exit(don't own server)

**Additional context**
Doom mod spawns through the roof, can't explore dimensions properly without having to fight endlessly.

**Comment by itsdinkd** [comment]
Seems like a server issue to me. i recommend having the server owner reduce entity-broadcast-range in their server properties. That is what makes mobs spawn past render distance.
