### ISSUE TITLE
[BUG] Immersive Engineering Alloy Kiln is uncraftable

### ISSUE THREAD

**Issue by TDHooligan** [itsdinkd/AQM3#76]
**Modpack Version**
1.8
**Minecraft Version**
1.18.1
**Describe the bug**
Alloy kiln recipe for Immersive Engineering conflicts with Cream Bricks from Domum Ornamentum

**To Reproduce**
1. Attempt to craft Alloy Kiln
2. Get Cream Bricks

**Expected behavior**
1. Alloy Kiln will be built, or a means to handle the conflicting recipe will show.

**Screenshots**

![image](https://user-images.githubusercontent.com/6061314/162641362-4b18b5cb-da4d-4c89-855d-adc0775ec4f6.png)
![image](https://user-images.githubusercontent.com/6061314/162641378-c0bb19be-edb8-4a78-9ff1-633ea777755d.png)

**Comment by pixelizedgaming** [comment]
Bro ur supposed to use sand, not sandstone
