### ISSUE TITLE
[BUG] Cooking For Blockheads cow production rate set too low

### ISSUE THREAD

**Issue by TDHooligan** [itsdinkd/AQM3#77]
**Modpack Version**
1.8
**Minecraft Version**
1.8,1
**Describe the bug**
The config for the cow in a jar makes it create 0.5 mB/t, which is less than 1 mB, meaning it creates zero due to, presumably, creating a non-integer volume. I don't really think 1 mB/t is enough milk to justify the rate being this slow.

**To Reproduce**
1. Place cow in a jar
2. Watch as no milk is created
 
**Expected behavior**
Milk is created

**Comment by itsdinkd** [comment]
changed to mod default, 1

will be on next release
