### ISSUE TITLE
[Bug] AQM3 Angel Ring (and many other items) not craftable

### ISSUE THREAD

**Issue by DemonGamingLP** [itsdinkd/AQM3#78]
Due to the missing recipe of the Enchanter's Pearl and the Nefarious Essence being unobtainable it is impossible to craft the Twist and the Infinitum (required for the Angel ring) while also taking a good weapon from the players that take the curses of the ring.

along with that the Ultimate Catalyst seems to be unobtainable as there is no craftable recipe for Ultimate nuggets, Ultimate ingots or Ultimate blocks.

I do not know if Morgan is obtainable due to not knowing the mod itself. JEI shows no recipe, thats why i mention it here. 

everything else seems obtainable.

(also, idk to which point it would be possible, to further advance the recipe you could replace all Blue Skies trophys in that recipe to the highest version of it, currently they are at bronze while each of them has a silver, gold and...platinum? version.)

**Comment by itsdinkd** [comment]
Please use the templates provided when opening up issues.

**Comment by DemonGamingLP** [comment]
huh?i was pretty sure i did since i know i needed to open up the curseforge website to lookup the version; my bad then, sorry!

**Comment by itsdinkd** [comment]
There is a ultimate ingot recipe. We do not use ultimate nuggets nor blocks. Not sure where you got those from

Morgan is not something you craft. It's something you get from casting the correct spell with the needed mana. 

I will fix the angel recipe on next update. Again next time you open a issue please use the provided templates

**Comment by itsdinkd** [comment]
Can you send me the file under logs/kubejs/server.txt?

**Comment by DemonGamingLP** [comment]
[server.txt](https://github.com/itsdinkd/AQM3/files/8592288/server.txt)

recipe missing in singleplayer aswell as in multiplayer.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/166127677-1d5ca55e-cc9b-4476-9497-6a4825af470e.png)

???

**Comment by itsdinkd** [comment]
issue was due to REI not showing all categories until you  refresh it. f

**Comment by DemonGamingLP** [comment]
Reopening this due to latest update still having the issues: you either need to recreate the enchanters pearl and the twist/the infinitum recipes or enable the special drops: the nefarious essence you need for both of them only are available through the wither WHILE speical drops for the enigmatica ring are enabled -> enabling the pearl effectively didnt change anything. (config mentioned here:  #79 )

also what do you mean with refreshing it? updating the modpack to 1.9, going into singleplayer still doesnt show the category with ultimate crafting for the ultimate ingot.(still does display the exact same recipes as shown above screenshots in modpack version 1.9). (the ultimate singularity was available in both modpack versions, with previously rei and now jei.)

[server.txt](https://github.com/itsdinkd/AQM3/files/8598679/server.txt)

sending the server.txt of the singleplayer attempt in modpack version 1.9 just in case you would ask for it again in the next answer.

**Comment by itsdinkd** [comment]
The category not showing for you is an issue with JEI. You will need to report it to the developer, mezz. If you view all categories it will start showing the missing categories when you view the individual recipe.
