### ISSUE TITLE
Double Jump issue in 1.0.2

### ISSUE THREAD

**Issue by elivicious** [itsdinkd/AQM3#8]
When holding space bar the game will nonstop auto jump even with auto jump off. Jump height also is now 2 blocks high. When jumping in sprint it will cease all momentum and make you jump straight up.

**Comment by jackwiffs** [comment]
I have had this issue too. though it only occurs when I log into a sever that has world from an older version, when it was updated to the 1.0.2. If I create a new world in single player it does not occur.

**Comment by itsdinkd** [comment]
This was addressed already in discord. its due to pmmo. you can find a fix in the aqm3 release channel
