### ISSUE TITLE
[BUG] Endurance every 8 levels does not raise hearts as listed in FAQ

### ISSUE THREAD

**Issue by JHTallboy** [itsdinkd/AQM3#85]
**1.0.2b**

**1.18.2**

**Describe the bug**
Leveling Endurance every 8 levels does not raise hearts as listed in FAQ.
**To Reproduce**
1. self damaged myself with magma block to raise endurance
2. leveled myself up to 8 and 16 in endurance
**Expected behavior**
expected to gain one heart every 8 levels in endurance, did not gain
**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by JHTallboy** [comment]
update, at 16 endurance i gained half a heart

**Comment by itsdinkd** [comment]
Take a screenshot of your PMMO stats using the /pmmo command to open it up.

**Comment by itsdinkd** [comment]
actually nevermind. I see the issue. btw, its not going to be every 8, but every 10 you get half a heart.

**Comment by JHTallboy** [comment]
sounds good, i was just basing it off what was in the faq and wanted to bring it to your attention. appreciate the response!

**Comment by itsdinkd** [comment]
much appreciated
