### ISSUE TITLE
[BUG] missing recipe for advanced circuit from mekanism

### ISSUE THREAD

**Issue by JHTallboy** [itsdinkd/AQM3#86]
**1.0.2b**

**1.18.2**

**Describe the bug**
advanced circuit in mekanism does not have a recipe available, blocking progression
**To Reproduce**

**Expected behavior**
a recipe for advanced circuit from mekanism
**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by tgokz** [comment]
removing/commenting out the following line in the techtiers.js file in kubejs\server_scripts\techprogress fixed this:
event.remove({id: "mekanism:control_circuit/advanced"})

**Comment by itsdinkd** [comment]
fixed in upcoming update
