### ISSUE TITLE
[BUG] game crashes when crafting gobber bread

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM3#87]
**Modpack Version**
1.0.2b
**Minecraft Version**
1.18.2
**Describe the bug**
Game crashes when crafting bread from the gobber mod

**To Reproduce**
1. craft gobber bread (blue variant. haven't tried with the other)
2. Game goes OOF

**Expected behavior**
should craft those tasty breads

**Crash log or latest.log.log**
https://paste.corebot.dev/ceriwemaxa.rb

**Additional context**
:(

**Comment by itsdinkd** [comment]
Origins cook is broken, disabled
