### ISSUE TITLE
Items in hand / Food Causes Client Crash - Cannot invoke "net.minecraft.core.holder.m_203633_()" Condition is null.

### ISSUE THREAD

**Issue by MisterGrace** [itsdinkd/AQM3#89]
I have no idea at this point, i have tested and it seems that i keep randomly crashing while using food items. Origins keeps getting mentioned with prevent item usage. 
This issue happened on 1.0.1b, so I updated to see if maybe it was caused by something else. And alas, the exact same crash log happened again. The server doesn't always show the crash log. Indicating it may be more Client Side based? Attempted with a clean profile and issue still persisted. So maybe player profile? I haven't tested that yet. But with these long load times i've been testing this for 2 hours now trying to find the EXACT issue. Will pick it back up tomorrow. 

Of course a few names / numbers are different as i was using different food items. But not many changes between the longs using N++ and compare feature. 

Maybe you can take a closer look and point me in a direction to be more helpful! 👍 

Dedicated Server;

These logs are for different times but they all show basically the same thing, 

Client Side LOG file 1.0.1b
[crash 6-3-22 936.txt](https://github.com/itsdinkd/AQM3/files/8836950/crash.6-3-22.936.txt)

Client Side LOG file. 1.0.2b
[crash 6-3-22 1008 1.0.2.txt](https://github.com/itsdinkd/AQM3/files/8836947/crash.6-3-22.1008.1.0.2.txt)

Server Side LOG file
[server side LOG  6-3-22 952.txt](https://github.com/itsdinkd/AQM3/files/8836948/server.side.LOG.6-3-22.952.txt)

**Comment by itsdinkd** [comment]
isssue what is your origin?

**Comment by MisterGrace** [comment]
My apologize, It was the Elytra, It was the Item check that was causing the crash. When ever I would right click rings from the goblins Modpack it failed finding the armor value and would crash the client.

**Comment by MisterGrace** [comment]
Cheap fix may be a datapack that removed the armor check value. Until the dev gets it working as intended.

**Comment by itsdinkd** [comment]
Theres a whole bunch of issues with Origins, most origins are causing crashes. I most likely am going to remove unfortunately...

there is another similar origin type mode called CeRes which I might add in its place depending on how OP it is or isn't.,
