### ISSUE TITLE
Gobber ore in overworld not spawning.

### ISSUE THREAD

**Issue by jackwiffs** [itsdinkd/AQM3#9]
Gobber ore was not generating in the overworld and mining dimension. The original world was a server world. As of 1.0.2, I deleted and reinstalled the pack with curse launcher. Create a new solo world, no ores seemed to spawn still and was double checked by adding the scanner mod to look for the ore. The ore does generate properly in both the Nether and End.

**Comment by elivicious** [comment]
Can confirm no gobber ore spawning in overworld. Took a single chunk from 0 to bedrock 100% stripmine to make sure. Zero gobber.

**Comment by Houyami** [comment]
Reminder: Gobber Ore (not deepslate gobber) Spawns from Y0 to Y40. Deepslate is Y0 to -Y64

**Comment by jackwiffs** [comment]
As a note, I found neither Gobber in stone or deepslate and no lucky stone and lucky deepslate in overworld and mining world.
I will try to find some time to try and figure it out as it might not be duplicable on all computers. To see if I can recreate it.

**Comment by jackwiffs** [comment]
issue found:
the file "config\gobber-general" was missing the following code when ever a fresh install was made. Causeing the ore not to spawn in new worlds

#Gobber Lucky Block Generation
[gobber2_lucky_block]
	#Generate Gobber Lucky Block in the world [true / false]
	gobberLuckyBlockGeneration = true
	#Size of Gobber Lucky Block pockets [0-100, default: 4]
	#Range: 0 ~ 100
	gobberLuckyBlockSize = 4
	#Chances of Gobber Lucky Block pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberLuckyBlockChance = 20
	#Minimal height for Gobber Lucky Block pocket generation, [0-384, default: 1]
	#Range: 0 ~ 384
	gobberLuckyBlockMinHeight = 1
	#Maximal height for Gobber Lucky Block pocket generation [0-384, default: 255]
	#Range: 0 ~ 384
	gobberLuckyBlockMaxHeight = 255

#Gobber Lucky Block Deepslate Generation
[gobber2_lucky_block_deepslate]
	#Generate Gobber Lucky Block Deepslate in the world [true / false]
	gobberLuckyBlockDeepslateGeneration = true
	#Size of Gobber Lucky Block Deepslate pockets [0-100, default: 4]
	#Range: 0 ~ 100
	gobberLuckyBlockDeepslateSize = 4
	#Chances of Gobber Lucky Block Deepslate pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberLuckyBlockDeepslateChance = 20
	#Minimal height for Gobber Lucky Block Deepslate pocket generation, [-64 to 0, default: -64]
	#Range: -64 ~ 0
	gobberLuckyBlockDeepslateMinHeight = -64
	#Maximal height for Gobber Lucky Block Deepslate pocket generation [-64 to 0, default: 0]
	#Range: -64 ~ 0
	gobberLuckyBlockDeepslateMaxHeight = 0

#Gobber Ore Generation
[gobber2_ore]
	#Generate Gobber Ore in the world [true / false]
	gobberOreGeneration = true
	#Size of Gobber Ore pockets [0-100, default: 4]
	#Range: 0 ~ 100
	gobberOreSize = 4
	#Chances of Gobber Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreChance = 15
	#Minimal height for Gobber Ore pocket generation, [0-255, default: 20]
	#Range: 0 ~ 384
	gobberOreMinHeight = 0
	#Maximal height for Gobber Ore pocket generation [0-255, default: 30]
	#Range: 0 ~ 384
	gobberOreMaxHeight = 30

#Gobber Ore Deepslate Generation
[gobber2_ore_deepslate]
	#Generate Gobber Ore Deepslate in the world [true / false]
	gobberOreDeepslateGeneration = true
	#Size of Gobber Ore Deepslate pockets [0-100, default: 4]
	#Range: 0 ~ 100
	gobberOreDeepslateSize = 4
	#Chances of Gobber Ore Deepslate pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberOreDeepslateChance = 20
	#Minimal height for Gobber Ore Deepslate pocket generation, [-64 to 0, default: -64]
	#Range: -64 ~ 0
	gobberOreDeepslateMinHeight = -64
	#Maximal height for Gobber Ore Deepslate pocket generation [-64 to 0, default: 0]
	#Range: -64 ~ 0
	gobberOreDeepslateMaxHeight = 0

**Comment by itsdinkd** [comment]
> 

All of this is in the config already. Also those are default values.

https://pastebin.com/Z9CNPrZv

**Comment by jackwiffs** [comment]
Might be wrong about what in the config is messed up, but deleting the config and using default fixes the ore not generating.
So i am not sure why then.
