### ISSUE TITLE
[BUG] HT's TreeChop does not work.

### ISSUE THREAD

**Issue by SparkySnips** [itsdinkd/AQM3#90]
**Modpack Version**
1.0.3b
**Minecraft Version**
1.18.2 (1.18.3? Curse/Minecraft say two different things I think, it's the latest on curse)
**Describe the bug**
HT's TreeChop simply does not work 90% of the time. Randomly it will spawn a TreeChop log, but will simply break and not follow the behavior of a TreeChop log. (Standard behavior is that breaking it will spawn a smaller log, over and over, until the tree in it's entirety breaks)
In game settings for TreeChop do not change this behavior; I have tried them. |
This occurs with both modded and vanilla tools / trees.

**To Reproduce**
Attempt to chop a tree with HT's TreeChop

**Expected behavior**
HT's TreeChop will function normally and chop the tree.

**Screenshots**
N/A

**Crash log or latest.log.log**
(Attached, pastebin does not allow a log file of this size)

**Additional context**
No tweaks have been made to configs, the pack is as it was when it was first installed other than controls and altering TreeChop settings, but these have not affected the functionality of TreeChop. 
The only time it worked consistently was when our server lagged constantly for several minutes for some odd reason. 
Same behavior in singleplayer. 
[latest.log](https://github.com/itsdinkd/AQM3/files/8865600/latest.log)

**Comment by EclipsePlays1181** [comment]
I'm having this same issue on 1.0.2b, and I've tried using silent gear's saws instead, and it just crashes (will bring this up in another thread)

**Comment by itsdinkd** [comment]
Due to multi mine and their tag system not working. I have removed MultiMine in the next update until it gets fixed by the developer.
