### ISSUE TITLE
[BUG] Silent Gear Saws cause crash(?)

### ISSUE THREAD

**Issue by EclipsePlays1181** [itsdinkd/AQM3#91]
**Modpack Version**
1.0.2b
**Minecraft Version**
1.18.2
**Describe the bug**
Attempts to use SGear's (Silent Gear) Saws have been met with a few frames of only that block dropping, followed by a black screen and no response, requiring user to kill process.

**To Reproduce**
Disable HT's TreeChop (also bugged, more in another thread.)
Use SGear Dark Oak Saw (likely can be any, have only tested Dark Oak) on Dark Oak Logs or Zelkova Logs (likely can be any, have only tested on preceding.)
Black screen and no input accepted.

**Expected behavior**
All connected logs would break and drop as items.

**Screenshots**
Unavailable to send video

**Crash log or latest.log.log**
Log is too large for Pastebin or Crashy, what should I use as alternative?

**Comment by itsdinkd** [comment]
this will need to  be reported to the developer of silent gear, I unfortunately cannot do anything to fix this
