### ISSUE TITLE
[BUG] Joining server taking 20+ minutes and failing

### ISSUE THREAD

**Issue by tincopper2** [itsdinkd/AQM3#94]
**Modpack Version**
1.0.3b
**Minecraft Version**
1.18.2
**Describe the bug**
After starting up the game and connecting to the default server from a fresh installation using the bundled java runtime with the current version of minecraft and on forge 40.1.20, gets stuck on this section of the log:
`[17:25:34] [Render thread/INFO]: Adding 27515 ingredients`
the instance then runs with minimal cpu usage for an extended period of time and fails to connect to the server, maintaining the message on screen "Joining world..."
I have allocated max 10G ram min 2G and was able to connect initially, but the game crashed during character creation.
I have since tried reinstalling the game, repairing the profile, attempting to use JDK 17.0.3.1 to no avail.
My username in the game is SirRaum
This is the error returned when I crashed from the game during character creation:
```
[16:50:23] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[16:50:23] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[16:50:23] [Render thread/INFO]: Stopping JEI
```

**To Reproduce**
Download latest version of modpack 1.0.3b
Connect to default server
Crash during character creation
Try to reconnect

**Expected behavior**
Successful and timely reconnect occurs with no crashing

**Comment by itsdinkd** [comment]
Known issue and posted on almost every change log.

**Comment by itsdinkd** [comment]
Bandaid solution is to join a single player world, once that's loaded, go into window mode and join your server. do not touch anything, no clicking. if you do, you can freeze java. let it load it will take 2-3 minutes this way.
