### ISSUE TITLE
[BUG] Several Cyclic machines/items unobtainable due to *believed* component recipe oversight

### ISSUE THREAD

**Issue by SparkySnips** [itsdinkd/AQM3#95]
**Modpack Version**
1.0.3b
**Minecraft Version**
1.18.2 (1.18.3? Curse/Minecraft say two different things I think, it's the latest on curse)
**Describe the bug**
Cyclic compressed cobblestone is unobtainable due to Compressium cobblestone taking precedence in crafting; Compressium cobblestone is not able to be used in Cyclic recipes, thus rendering many Cyclic items unobtainable.
*NOTE*: It is assumed this is an oversight due to some of the recipes being basic such as the Cyclic handbook, if intentional please ignore.

**To Reproduce**
Craft compressed cobblestone (3x3), yields Compressium cobblestone.
Attempt to craft a Cyclic machine requiring Cyclic compressed cobblestone with Compressium cobblestone.

**Expected behavior**
Compressium compressed cobblestone would be able to be used in place of the Cyclic variant.

**Screenshots**
N/A

**Crash log or latest.log.log**
N/A (Recipe issue)

**Additional context**
N/A

**Comment by itsdinkd** [comment]
So we do have polymorph which is supposed to allow you to pick what you want to craft if a conflicting recipe occurs. 

![image](https://user-images.githubusercontent.com/35115304/173443679-f58d7a72-1ae7-4c32-8024-5a6a11f6e0db.png)
![image](https://user-images.githubusercontent.com/35115304/173443701-7ac39c68-0aa0-4d59-bd04-07ceef3ba599.png)
![image](https://user-images.githubusercontent.com/35115304/173443710-ec55433c-ec37-4135-9ca8-afe5afd2ac6a.png)
![image](https://user-images.githubusercontent.com/35115304/173443733-da71b669-e014-42fb-92bd-6bd88cba7133.png)
