### ISSUE TITLE
[BUG] Unable to make Assembly Line Machines' Steel Ingot

### ISSUE THREAD

**Issue by JessicaSkye** [itsdinkd/AQM3#97]
**Modpack Version**
1.0.3b

**Minecraft Version**
1.18.2

**Describe the bug**
Mixing Ground Coal and Ground Iron in a Fluid Bath with Lava results in an "Invalid Recipe" and losing all ingredients (turned to Sludge) when draining the Fluid Bath

**To Reproduce**
1. Put Lava in Fluid Bath
2. Add Ground Coal and Ground Iron
4. Attempt to stir with a Pure Iron Stirring Stick
5. Note the "Invalid recipe" action message

**Expected behavior**
Steel to be made from the provided ingredients

**Additional context**
The recipe for Steel Ingots also do not show in JEI, despite the fact that other Fluid Bath recipes do.
Order of ingredients placed in the Fluid Bath *does* matter, but the recipe fails despite what order they're placed.

**Comment by JessicaSkye** [comment]
There seems to be some inconsistency between the KubeJS scripts here in the GH repo, and the scripts provided in the 1.0.3b server pack I obtained from CurseForge.

Within the server pack I downloaded, directly from the Google Drive link provided on CurseForge, within `./kubejs/server_scripts/remove.js`, there are far more entries that are being removed than what this repo shows in the same file.

Most notably, various items from Reliquary (such as the Rod of Lyssa, and the Rending Gale), and most importantly, the Steel Ingot from Assembly Line Machines.

The full file I acquired from the pack can be found [here](https://pastebin.com/6Ez7fKXr). I'm unsure why there would be such inconsistencies, but removing the Steel Ingot entry from this list resolves this issue.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/173443234-e0cac3cf-f1aa-4d1c-a7a5-c920107fd65f.png)
![image](https://user-images.githubusercontent.com/35115304/173443266-d065b359-f42d-4c2a-9315-56d3d190d403.png)


I havent changed a thing, im not sure what files your getting.... but rest assured, it will work in the next update. Make sure you delete your kubejs and mods folders always (for servers) before updating and moving what you downloaded into your server.

**Comment by itsdinkd** [comment]
This repo is slightly behind, apologies for that.

**Comment by JessicaSkye** [comment]
No worries, I just realized that myself.

To clarify, [this](https://drive.google.com/file/d/1zHeSc-tq9D7AFAmL9U_u_W3A4rhaomYl/view) is where I got the server pack, which is attached to the description for the 1.0.3b ZIP file on CurseForge.

I'm happy to hear it'll be sorted out in future versions though, thank you! :)
