### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Whitealbum0** [itsdinkd/AQM3#98]
**Modpack Version**
AQM3-1.18.2-1.0.4b

**Minecraft Version**
1.18.2 forg-40.1.48

**Describe the bug**
Run through the forest. And there was an emergency stop

**To Reproduce**
Don't know how to do it

**Expected behavior**
----
**Screenshots**
https://prnt.sc/bPywZg1TDOkw

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*
https://crashy.net/7LNdOxG7lDJBLXAbQ0jy
**Additional context**
----

**Comment by itsdinkd** [comment]
Without being able to reproduce I cannot fix this.

Looks like a client side crash due to shaders
